### ISSUE TITLE
feature: client overview

### ISSUE THREAD

**Issue by alastairruhm** [alastairruhm/guidor_deprecated#1]
## client requirement overview

- [ ]  Register instance in guidor api server
- [ ]  Do backup action with target database that client runs on
- [ ]  Commit an event whether the backup action success or not

**Comment by alastairruhm** [comment]
This issue was moved to alastairruhm/guidor#1
